# Generated by Django 6.0.3 on 2026-04-05 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ชื่อ-นามสกุล ผู้แต่ง')),
                ('nationality', models.CharField(blank=True, max_length=100, null=True, verbose_name='สัญชาติ')),
            ],
            options={
                'verbose_name': 'ผู้แต่ง',
                'verbose_name_plural': 'ผู้แต่ง',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อหมวดหมู่')),
                ('description', models.TextField(blank=True, null=True, verbose_name='รายละเอียด')),
            ],
            options={
                'verbose_name': 'หมวดหมู่',
                'verbose_name_plural': 'หมวดหมู่',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ชื่อหนังสือ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='เรื่องย่อ / รายละเอียด')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='ภาพหน้าปก')),
                ('total_copies', models.PositiveIntegerField(default=1, verbose_name='จำนวนเล่มทั้งหมด')),
                ('available_copies', models.PositiveIntegerField(default=1, verbose_name='จำนวนเล่มที่พร้อมยืม')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='บันทึกเมื่อ')),
                ('authors', models.ManyToManyField(blank=True, related_name='books', to='library_app.author', verbose_name='ผู้แต่ง')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='library_app.category', verbose_name='หมวดหมู่')),
            ],
            options={
                'verbose_name': 'หนังสือ',
                'verbose_name_plural': 'หนังสือ',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(auto_now_add=True, verbose_name='วันที่ยืม')),
                ('due_date', models.DateField(verbose_name='วันที่กำหนดคืน')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='วันที่คืนจริง')),
                ('status', models.CharField(choices=[('borrowed', 'กำลังยืม'), ('returned', 'คืนแล้ว'), ('overdue', 'เลยกำหนดคืน')], default='borrowed', max_length=20, verbose_name='สถานะการคืน')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to='library_app.book', verbose_name='หนังสือ')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ยืม')),
            ],
            options={
                'verbose_name': 'การยืมหนังสือ',
                'verbose_name_plural': 'การยืมหนังสือ',
                'ordering': ['-borrow_date', '-id'],
            },
        ),
    ]
