# Generated by Django 6.0.3 on 2026-04-05 15:39

from django.db import migrations, models


def create_teacher_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='Teacher')


def remove_teacher_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name='Teacher').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_create_student_librarian_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ebook_pdf',
            field=models.FileField(blank=True, help_text='อัปโหลด PDF สำหรับอ่านในตัวอ่านดิจิทัล (ถ้ามี)', null=True, upload_to='ebooks/', verbose_name='ไฟล์ e-book (PDF)'),
        ),
        migrations.AddField(
            model_name='book',
            name='ebook_text',
            field=models.TextField(blank=True, default='', help_text='ถ้าไม่มี PDF ให้วางข้อความ แบ่งหน้าด้วยบรรทัด <<<PAGE>>> ระหว่างหน้า', verbose_name='เนื้อหา e-book (ข้อความ)'),
        ),
        migrations.RunPython(create_teacher_group, remove_teacher_group),
    ]
