# Generated by Django 6.0.3 on 2026-04-05 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_rename_borrow_user_id_to_borrower_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='เบอร์โทรศัพท์')),
                ('birth_date', models.DateField(verbose_name='วันเกิด')),
                ('national_id', models.CharField(blank=True, default='', help_text='กรอกเมื่อสมัครในฐานะครู', max_length=13, verbose_name='เลขบัตรประชาชน')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='library_profile', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้')),
            ],
            options={
                'verbose_name': 'โปรไฟล์สมาชิกห้องสมุด',
                'verbose_name_plural': 'โปรไฟล์สมาชิกห้องสมุด',
            },
        ),
    ]
