# Generated by Django 6.0.3 on 2026-04-05 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='grade_level',
            field=models.CharField(choices=[('p1', 'ป.1'), ('p2', 'ป.2'), ('p3', 'ป.3'), ('p4', 'ป.4'), ('p5', 'ป.5'), ('p6', 'ป.6')], default='p1', max_length=8, verbose_name='ระดับชั้นที่เหมาะสม'),
        ),
        migrations.AddField(
            model_name='book',
            name='learning_area',
            field=models.CharField(choices=[('thai', 'ภาษาไทย'), ('math', 'คณิตศาสตร์'), ('science', 'วิทยาศาสตร์และเทคโนโลยี'), ('social', 'สังคมศึกษา ศาสนาและวัฒนธรรม'), ('health', 'สุขศึกษาและพลศึกษา'), ('art', 'ศิลปะ'), ('career', 'การงานอาชีพ'), ('foreign', 'ภาษาต่างประเทศ'), ('other', 'อื่นๆ / รวมหลายกลุ่ม')], default='other', max_length=32, verbose_name='กลุ่มสาระการเรียนรู้'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='grade_level',
            field=models.CharField(blank=True, choices=[('p1', 'ป.1'), ('p2', 'ป.2'), ('p3', 'ป.3'), ('p4', 'ป.4'), ('p5', 'ป.5'), ('p6', 'ป.6')], default='', max_length=8, verbose_name='ระดับชั้น'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='student_id',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='รหัสนักเรียน'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='library_app.category', verbose_name='หมวดหมู่ (เพิ่มเติม)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันเกิด'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='national_id',
            field=models.CharField(blank=True, default='', max_length=13, verbose_name='เลขบัตรประชาชน'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='เบอร์โทรศัพท์'),
        ),
    ]
